language: go
sudo: true

go:
  - 1.5.3
  - 1.6
  - tip

env:
  global:
    - GO15VENDOREXPERIMENT=1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnl-3-dev libnl-genl-3-dev

#install: true
script:
  - make validate
#  - make godep
  - make bin

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - go: tip

